export const tracks = [
  {
    id: 1,
    num: '001',
    title: 'Drakensberg Dawn Chorus',
    location: 'Cathedral Peak, KZN',
    lat: -28.85,
    lng: 29.22,
    desc: 'Several hundred bird species at first light, 2,900m altitude. Thin air gives voices an extraordinary clarity.',
    tag: 'New',
    tagColor: 'forest',
    price: 480,
    duration: '61:04',
    format: '96kHz / 32-bit WAV',
    category: 'Wildlife',
    freqProfile: [0.3,0.6,0.9,0.7,0.5,0.8,1.0,0.9,0.6,0.4,0.7,0.8,0.5,0.3,0.6,0.9,0.7,0.4,0.8,1.0],
  },
  {
    id: 2,
    num: '002',
    title: 'Cederberg Cave Resonance',
    location: 'Wolfberg Arch, Western Cape',
    lat: -32.48,
    lng: 19.18,
    desc: 'Wind channelled through ancient sandstone caves. A low, sustained drone unlike anything synthesised.',
    tag: 'Weather',
    tagColor: 'rust',
    price: 620,
    duration: '33:18',
    format: '96kHz / 32-bit WAV',
    category: 'Acoustic',
    freqProfile: [0.8,0.9,1.0,0.9,0.8,0.9,0.7,0.8,0.9,1.0,0.8,0.7,0.9,1.0,0.8,0.7,0.9,0.8,0.7,0.9],
  },
  {
    id: 3,
    num: '003',
    title: 'Okavango Night Flood',
    location: 'Moremi Reserve, Botswana',
    lat: -19.3,
    lng: 23.2,
    desc: 'Floodwater arriving after the rains — hippos, frogs, the wet rush of a delta filling. 12 licences remaining.',
    tag: 'Limited',
    tagColor: 'faded',
    price: 890,
    duration: '78:41',
    format: '192kHz / 32-bit WAV',
    category: 'Wildlife',
    freqProfile: [0.4,0.5,0.7,0.9,1.0,0.8,0.6,0.9,0.7,0.5,0.8,1.0,0.7,0.4,0.6,0.9,0.8,0.5,0.7,0.9],
  },
  {
    id: 4,
    num: '004',
    title: 'Kalahari Midday Silence',
    location: '!Ae!Hai Reserve, Northern Cape',
    lat: -26.5,
    lng: 20.8,
    desc: 'The paradox of desert silence — wind, heat shimmer, a single lark. Recorded at 42°C on a flat-calm afternoon.',
    tag: 'Wildlife',
    tagColor: 'rust',
    price: 380,
    duration: '44:00',
    format: '96kHz / 32-bit WAV',
    category: 'Weather',
    freqProfile: [0.1,0.2,0.1,0.3,0.2,0.1,0.4,0.2,0.1,0.3,0.2,0.1,0.2,0.3,0.1,0.2,0.4,0.1,0.2,0.3],
  },
  {
    id: 5,
    num: '005',
    title: 'False Bay Winter Swell',
    location: 'Cape Point, Western Cape',
    lat: -34.35,
    lng: 18.49,
    desc: '3-metre swells on a headland cliff. Hydrophone and binaural capture — both underwater and above simultaneously.',
    tag: 'New',
    tagColor: 'forest',
    price: 540,
    duration: '55:29',
    format: '96kHz / 32-bit WAV',
    category: 'Weather',
    freqProfile: [0.6,0.8,1.0,0.9,0.7,0.8,1.0,0.9,0.6,0.7,0.9,1.0,0.8,0.6,0.7,0.9,1.0,0.8,0.6,0.8],
  },
  {
    id: 6,
    num: '006',
    title: 'Amphitheatre Echo Study',
    location: 'Royal Natal, KZN',
    lat: -28.72,
    lng: 28.89,
    desc: '3km natural amphitheatre basalt wall. IR impulse captures, long reverb tails, and raw atmospheric passes.',
    tag: 'Acoustic',
    tagColor: 'rust',
    price: 740,
    duration: '28:55',
    format: '192kHz / 32-bit WAV',
    category: 'Acoustic',
    freqProfile: [0.5,0.7,0.8,0.9,0.7,0.5,0.8,1.0,0.9,0.6,0.4,0.7,0.9,1.0,0.8,0.5,0.7,0.9,0.8,0.6],
  },
];

export const mapLocations = [
  { id: 1, title: 'Drakensberg Dawn Chorus', loc: 'Cathedral Peak, KZN', lat: -28.85, lng: 29.22, isNew: true },
  { id: 2, title: 'Cederberg Cave Resonance', loc: 'Wolfberg Arch, WC', lat: -32.48, lng: 19.18, isNew: false },
  { id: 3, title: 'Okavango Night Flood', loc: 'Moremi Reserve, Botswana', lat: -19.3, lng: 23.2, isNew: false },
  { id: 4, title: 'Kalahari Midday Silence', loc: '!Ae!Hai Reserve, NC', lat: -26.5, lng: 20.8, isNew: false },
  { id: 5, title: 'False Bay Winter Swell', loc: 'Cape Point, WC', lat: -34.35, lng: 18.49, isNew: true },
  { id: 6, title: 'Amphitheatre Echo Study', loc: 'Royal Natal, KZN', lat: -28.72, lng: 28.89, isNew: true },
  { id: 7, title: 'Richtersveld Night Sky', loc: 'Richtersveld NP, NC', lat: -28.2, lng: 17.1, isNew: false },
  { id: 8, title: 'Mapungubwe Dry Season', loc: 'Mapungubwe NP, Limpopo', lat: -22.18, lng: 29.27, isNew: true },
];

export const teamMembers = [
  {
    initials: 'S',
    name: 'Sipho Dlamini',
    role: 'Lead Recordist & Founder',
    bio: 'Former acoustic ecologist for SANParks. Left to record full-time in 2018. Responsible for 60% of the catalogue. Has slept in a hide for 48 hours waiting for a weather event.',
    kit: 'MKH 8020 · MixPre-10 II',
    speciality: 'Weather · Dawn sessions',
    sessions: 214,
  },
  {
    initials: 'L',
    name: 'Lena Fischer',
    role: 'Hydrophone Specialist',
    bio: 'Marine biologist turned field recordist. Handles all aquatic and underwater sessions. Designed VELDTONE\'s dual-capture rig for simultaneous above/below recording.',
    kit: 'H2a Hydrophone · DPA 4060',
    speciality: 'Water · Coastal',
    sessions: 88,
  },
  {
    initials: 'R',
    name: 'Ruan van der Berg',
    role: 'Cave & Acoustic Spaces',
    bio: 'Geologist by training. Spends most of his time underground. Pioneered VELDTONE\'s IR impulse response capture methodology for the Cederberg cave series.',
    kit: 'MKH 50 · Zoom F6',
    speciality: 'Caves · Stone acoustics',
    sessions: 61,
  },
  {
    initials: 'A',
    name: 'Amara Diallo',
    role: 'Wildlife & Savanna',
    bio: 'Based in Botswana six months of the year. Manages all trans-border expedition sessions. Speaks four languages — critical for negotiating reserve access.',
    kit: 'Telinga Parabolic · MixPre-6 II',
    speciality: 'Wildlife · Night sessions',
    sessions: 103,
  },
];

export const testimonials = [
  { quote: 'We licensed the Okavango Night Flood for a documentary score bed. Our composer said it was the first time a field recording made him cry in a mixing suite. We used 38 minutes unedited.', name: 'Priya Naidoo', role: 'Post-Production Supervisor', company: 'Netflix' },
  { quote: 'The Cave Resonance gave us an IR we\'ve been chasing for three years. Dropped it into our convolution reverb and the whole ambient team went quiet for about two minutes.', name: 'Marcus Tetteh', role: 'Lead Audio Designer', company: 'Naughty Dog' },
  { quote: 'Three seasons of our wildlife series. VELDTONE doesn\'t just hand you a file — they hand you a place. The metadata, the field notes, the atmospheric conditions. Editorial integrity.', name: 'Fiona Ashworth', role: 'Series Sound Producer', company: 'BBC Studios' },
  { quote: 'Our client wanted authentic Africa. One email, a custom commission, eight weeks later we had something the client framed on their boardroom wall.', name: 'Zanele Mokoena', role: 'Creative Director', company: 'Ogilvy' },
  { quote: 'We built a permanent acoustic installation using the Drakensberg Dawn Chorus. Visitors stand in a dark room for four minutes and report it as the most affecting exhibit in the building.', name: 'Dr. Alistair Rowe', role: 'Curator, Natural World', company: 'Smithsonian' },
  { quote: 'For our SS26 runway we wanted something that felt like land — not fashion. The Kalahari Midday Silence under forty models walking. The fashion press called it the quietest show they\'d ever loved.', name: 'Christophe Lemaire', role: 'Creative Director', company: 'Lemaire' },
];

export const trustedBy = [
  { name: 'Netflix', field: 'Film & Streaming', color: '#E50914', font: 'playfair', weight: 700, size: 22 },
  { name: 'NAUGHTY DOG', field: 'Game Studio', color: '#003087', font: 'courier', weight: 700, size: 13 },
  { name: 'Snøhetta', field: 'Architecture', color: '#1a1a1a', font: 'cormorant', weight: 300, size: 20, italic: true },
  { name: 'MERCEDES AMG', field: 'Automotive', color: '#1a1a1a', font: 'courier', weight: 700, size: 11 },
  { name: 'Smithsonian', field: 'Museum & Cultural', color: '#5B3A29', font: 'cormorant', weight: 400, size: 18 },
  { name: 'BBC STUDIOS', field: 'Broadcast', color: '#CC0000', font: 'playfair', weight: 900, size: 16 },
  { name: 'Lemaire', field: 'Fashion House', color: '#1a1a1a', font: 'cormorant', weight: 300, size: 22, italic: true },
  { name: 'WWF — SA', field: 'Conservation', color: '#2D6A2D', font: 'courier', weight: 700, size: 12 },
  { name: 'Ogilvy', field: 'Advertising', color: '#E03A1E', font: 'playfair', weight: 700, size: 20 },
  { name: 'Condé Nast', field: 'Publishing', color: '#2C2C4A', font: 'cormorant', weight: 400, size: 19, italic: true },
];

export const faqs = [
  { q: 'Are these recordings truly unprocessed?', a: 'Every master file is delivered exactly as captured — no EQ, no noise reduction, no normalisation. What you receive is the raw 32-bit float capture. If you want a processed version for a specific use case, we can prepare one on request, but the master remains untouched. Always.' },
  { q: 'What does a Studio Licence actually allow me to do?', a: 'The Studio Licence covers broadcast, streaming, film, games, and commercial advertising for productions up to R5 million budget. It\'s perpetual, covers up to three team members, and includes the full 96kHz/32-bit WAV file. Use it in as many projects as you like — no per-project restriction.' },
  { q: 'Can I commission a custom field recording?', a: 'Yes — and it\'s one of our favourite things to do. We take commissions for specific locations, time-of-year conditions, acoustic environments, or wildlife events. Lead time is typically 4–12 weeks. Custom commissions are priced under the Archive tier and include a full expedition brief and field report.' },
  { q: 'How are the files delivered?', a: 'Immediately after licensing, you receive a private download link valid for 14 days. Files are packaged as a ZIP containing the WAV master, a PDF field report with GPS coordinates, atmospheric conditions, equipment used, session notes, plus a BWAV metadata-embedded version ready for DAW import.' },
  { q: 'Do SAMRO or CAPASSO royalties apply?', a: 'No. VELDTONE recordings are environmental field captures — not musical compositions or performances. They fall outside the scope of SAMRO and CAPASSO\'s mandates entirely. You will not receive a royalty claim from any collecting society. This is confirmed in writing with every licence.' },
  { q: 'Can I request exclusivity on a recording?', a: 'Exclusivity windows are available under the Archive tier. We offer 12-month exclusive licensing — meaning we pull the recording from the catalogue for that period. Exclusivity is priced at a multiple of the Archive rate and subject to existing active licences.' },
];
